#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs/REPO_MAP.md'
IMPORT_RE = re.compile(r"(?:from\s+|import\s*\(|import\s+)(['\"])([^'\"]+)\1")
EXPORT_RE = re.compile(r"^export\s+(?:async\s+)?(?:function|class|interface|type|const|let|enum)\s+([A-Za-z0-9_]+)", re.M)


def render() -> str:
    lines = [
        '# DataFixer Repository Map',
        '',
        '> Generated by `python scripts/generate-repo-map.py`. Do not edit by hand.',
        '',
        '## Source modules',
        '',
    ]
    for path in sorted([*ROOT.joinpath('src').rglob('*.ts'), *ROOT.joinpath('src').rglob('*.tsx')]):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding='utf-8')
        exports = sorted(set(EXPORT_RE.findall(text)))
        imports = sorted({m.group(2) for m in IMPORT_RE.finditer(text) if m.group(2).startswith('.')})
        lines.append(f'### `{rel}`')
        lines.append('')
        lines.append(f'- Exports: {", ".join(f"`{x}`" for x in exports) if exports else "_(none detected)_"}')
        lines.append(f'- Local imports: {", ".join(f"`{x}`" for x in imports) if imports else "_(none)_"}')
        lines.append('')

    lines += ['## Verification entry points', '']
    for rel in [
        'tests/local/run-regression.sh',
        'tests/harness/harness-contract-check.py',
        'tests/harness/architecture-check.py',
        'scripts/verify.py',
        'scripts/production-preflight.sh',
        'scripts/production-gates.sh',
    ]:
        lines.append(f'- `{rel}`')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
            print('FAIL docs/REPO_MAP.md is stale; run python scripts/generate-repo-map.py')
            return 1
        print('PASS repo-map-check')
        return 0
    OUTPUT.write_text(content, encoding='utf-8')
    print(f'WROTE {OUTPUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
